channel_threads: 1
feed_threads: 1
db:
  user: __DB_NAME__
  password: __DB_PASS__
  host: localhost
  port: 5432
  dbname: __DB_NAME__
full_refresh: false
https_only: false
domain: http://__DOMAIN__
port: __PORT__
host_binding: 127.0.0.1

